import type { SettingOption } from './types';

/** Common IANA timezone options grouped by region. */
export const TIMEZONE_OPTIONS: SettingOption[] = [
  { label: 'UTC', value: 'UTC', description: 'Coordinated Universal Time' },
  { label: 'US/Eastern (ET)', value: 'America/New_York', description: 'UTC-5 / UTC-4 DST' },
  { label: 'US/Central (CT)', value: 'America/Chicago', description: 'UTC-6 / UTC-5 DST' },
  { label: 'US/Mountain (MT)', value: 'America/Denver', description: 'UTC-7 / UTC-6 DST' },
  { label: 'US/Pacific (PT)', value: 'America/Los_Angeles', description: 'UTC-8 / UTC-7 DST' },
  { label: 'US/Alaska', value: 'America/Anchorage', description: 'UTC-9 / UTC-8 DST' },
  { label: 'US/Hawaii', value: 'Pacific/Honolulu', description: 'UTC-10' },
  { label: 'Canada/Atlantic', value: 'America/Halifax', description: 'UTC-4 / UTC-3 DST' },
  { label: 'Canada/Newfoundland', value: 'America/St_Johns', description: 'UTC-3:30' },
  { label: 'Mexico City', value: 'America/Mexico_City', description: 'UTC-6 / UTC-5 DST' },
  { label: 'Sao Paulo', value: 'America/Sao_Paulo', description: 'UTC-3' },
  { label: 'Buenos Aires', value: 'America/Argentina/Buenos_Aires', description: 'UTC-3' },
  { label: 'London (GMT/BST)', value: 'Europe/London', description: 'UTC+0 / UTC+1 DST' },
  { label: 'Paris (CET)', value: 'Europe/Paris', description: 'UTC+1 / UTC+2 DST' },
  { label: 'Berlin (CET)', value: 'Europe/Berlin', description: 'UTC+1 / UTC+2 DST' },
  { label: 'Amsterdam (CET)', value: 'Europe/Amsterdam', description: 'UTC+1 / UTC+2 DST' },
  { label: 'Rome (CET)', value: 'Europe/Rome', description: 'UTC+1 / UTC+2 DST' },
  { label: 'Madrid (CET)', value: 'Europe/Madrid', description: 'UTC+1 / UTC+2 DST' },
  { label: 'Athens (EET)', value: 'Europe/Athens', description: 'UTC+2 / UTC+3 DST' },
  { label: 'Istanbul', value: 'Europe/Istanbul', description: 'UTC+3' },
  { label: 'Moscow', value: 'Europe/Moscow', description: 'UTC+3' },
  { label: 'Dubai', value: 'Asia/Dubai', description: 'UTC+4' },
  { label: 'Kolkata (IST)', value: 'Asia/Kolkata', description: 'UTC+5:30' },
  { label: 'Bangkok (ICT)', value: 'Asia/Bangkok', description: 'UTC+7' },
  { label: 'Singapore (SGT)', value: 'Asia/Singapore', description: 'UTC+8' },
  { label: 'Hong Kong (HKT)', value: 'Asia/Hong_Kong', description: 'UTC+8' },
  { label: 'Shanghai (CST)', value: 'Asia/Shanghai', description: 'UTC+8' },
  { label: 'Taipei (CST)', value: 'Asia/Taipei', description: 'UTC+8' },
  { label: 'Seoul (KST)', value: 'Asia/Seoul', description: 'UTC+9' },
  { label: 'Tokyo (JST)', value: 'Asia/Tokyo', description: 'UTC+9' },
  { label: 'Sydney (AEST)', value: 'Australia/Sydney', description: 'UTC+10 / UTC+11 DST' },
  { label: 'Melbourne (AEST)', value: 'Australia/Melbourne', description: 'UTC+10 / UTC+11 DST' },
  { label: 'Auckland (NZST)', value: 'Pacific/Auckland', description: 'UTC+12 / UTC+13 DST' },
  { label: 'Cairo (EET)', value: 'Africa/Cairo', description: 'UTC+2' },
  { label: 'Lagos (WAT)', value: 'Africa/Lagos', description: 'UTC+1' },
  { label: 'Nairobi (EAT)', value: 'Africa/Nairobi', description: 'UTC+3' },
  { label: 'Johannesburg (SAST)', value: 'Africa/Johannesburg', description: 'UTC+2' },
];
